# Copyright 2024-2026 SURF.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Query the WFO orchestrator GraphQL API and map results into render DTOs.

The end-user's OIDC token is forwarded per request as a Bearer credential; the orchestrator validates
it against the provider's userinfo endpoint and gates queries on its read groups. Every fetch returns
``None`` on any failure (transport, non-200, non-JSON, GraphQL errors) so callers can tell "failed"
apart from "empty"; a refusal of the caller's credentials instead raises :class:`WfoUnauthorizedError`.
"""

import json
from collections import Counter
from datetime import datetime

import requests
import structlog
from pydantic import BaseModel, computed_field

from amiss.nsi import REQUEST_TIMEOUT, session
from amiss.settings import settings

logger = structlog.get_logger(__name__)

# Concrete GraphQL subscription type names (auto-generated by orchestrator-core from the product
# base-type names). Tags are set per product by the orchestrator's migrations; see CLAUDE.md.
MDP2P_TYPE = "MultiDomainPoint2PointSubscription"
STP_TYPE = "ServiceTerminationPointSubscription"
SDP_TYPE = "ServiceDemarcationPointSubscription"
TOPOLOGY_TYPE = "TopologySubscription"
SWITCHING_SERVICE_TYPE = "SwitchingServiceSubscription"

CIRCUITS_QUERY = """
{ subscriptions(first: 500, filterBy: [{field: "tag", value: "MDP2P"}]) {
  page {
    subscriptionId description status startDate endDate
    ... on %(mdp2p)s { vc {
      circuitDescription serviceSpeed globalReservationId connectionId state
      saps { vlan stp { stpId stpName capacity labelGroup } } } }
    processes(filterBy: [{field: "target", value: "CREATE"}],
              sortBy: [{field: "startedAt", order: ASC}], first: 10) {
      page { createdBy startedAt lastStatus } }
  }
  pageInfo { totalItems }
} }
""" % {"mdp2p": MDP2P_TYPE}

STP_QUERY = """
{ subscriptions(first: 1000, filterBy: [{field: "tag", value: "STP"}]) {
  page { subscriptionId status
    ... on %(stp)s { stp { stpId stpName capacity labelGroup } } }
  pageInfo { totalItems }
} }
""" % {"stp": STP_TYPE}

SDP_QUERY = """
{ subscriptions(first: 1000, filterBy: [{field: "tag", value: "SDP"}]) {
  page { subscriptionId status
    ... on %(sdp)s { sdp { sdpName stps { stpId stpName capacity labelGroup } } } }
  pageInfo { totalItems }
} }
""" % {"sdp": SDP_TYPE}


# api_unavailable and inconsistent_data are subtypes of failed; see CLAUDE.md.
VALIDATION_FAILURES_QUERY = """
{ processes(filterBy: [{field: "lastStatus", value: "failed|inconsistent_data|api_unavailable"},
                       {field: "target", value: "VALIDATE|SYSTEM"}],
            sortBy: [{field: "startedAt", order: DESC}], first: 100) {
  page {
    processId workflowName workflowTarget lastStatus failedReason startedAt
    subscriptions(first: 1) { page { subscriptionId description } } }
  pageInfo { totalItems }
} }
"""

_REASON_LENGTH = 120


TOPOLOGY_QUERY = """
{ subscriptions(first: 1000, filterBy: [{field: "tag", value: "TOPOLOGY"}]) {
  page { subscriptionId status
    ... on %(topology)s { topology { topologyId topologyName } } }
  pageInfo { totalItems }
} }
""" % {"topology": TOPOLOGY_TYPE}

SWITCHING_SERVICE_QUERY = """
{ subscriptions(first: 1000, filterBy: [{field: "tag", value: "SWITCHINGSERVICE"}]) {
  page { subscriptionId status
    ... on %(switching_service)s { switchingservice { switchingServiceId switchingServiceName } } }
  pageInfo { totalItems }
} }
""" % {"switching_service": SWITCHING_SERVICE_TYPE}


class WfoUnauthorizedError(Exception):
    """The WFO refused the caller's credentials, rather than failing to answer.

    Worth keeping distinct from a fetch failure: the two look identical on screen, but this one is
    fixed by re-authenticating or being added to a group, not by waiting for an upstream to recover.
    """


# A refusal observed from the orchestrator is HTTP 200 with, per error, an ``error_type`` extension
# and the message "User is not authenticated" / "User is not authorized to query `x`". The extension
# is authoritative; the message is checked only to survive an oauth2-lib that predates it.
_AUTHZ_ERROR_TYPES = frozenset({"not_authenticated", "not_authorized"})


def _is_authz_error(errors: list) -> bool:
    """Return whether a GraphQL ``errors`` payload is a credentials refusal, not a real failure."""
    return any(
        (error.get("extensions") or {}).get("error_type") in _AUTHZ_ERROR_TYPES
        or "not auth" in str(error.get("message", "")).lower()
        for error in errors
        if isinstance(error, dict)
    )


def short_id(subscription_id: str | None) -> str | None:
    """Return the first 8 chars of a subscription id, which is what the list tables show."""
    return subscription_id[:8] if subscription_id else None


class CircuitRow(BaseModel):
    """A circuit row rendered in /circuits, built live from an MDP2P subscription."""

    subscription_id: str
    description: str | None = None
    start_time: str | None = None  # 'YYYY-MM-DD HH:MM:SS' (compact, wraps on the space)
    end_time: str | None = None
    source_stp: str | None = None  # the STP's name where it has one; source_stp_id is what joins to /stp
    source_stp_id: str | None = None
    source_vlan: str | None = None
    dest_stp: str | None = None
    dest_stp_id: str | None = None
    dest_vlan: str | None = None
    source: str | None = None  # 'stp (vlan N)' for the compact list; raw stp/vlan (above) shown on detail
    dest: str | None = None
    bandwidth: int | None = None
    state: str | None = None
    created_by: str | None = None  # 'Full Name <email>' from the WFO; the list shows created_by_name
    connection_id: str | None = None
    global_reservation_id: str | None = None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def short_id(self) -> str | None:
        return short_id(self.subscription_id)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def created_by_name(self) -> str | None:
        """The creator without the email, to keep the Created By column narrow in the list.

        The WFO reports ``Full Name <email>`` when the token carries both claims, and a bare name or
        email when it carries one; dropping everything from the first ``' <'`` leaves the full name
        in the first case and the single value it did report in the others.
        """
        return self.created_by.split(" <")[0] if self.created_by else self.created_by


class NamedSub(BaseModel):
    """A Topology or SwitchingService subscription: an id and a name."""

    subscription_id: str
    object_id: str | None = None
    name: str | None = None
    status: str | None = None


class StpSub(BaseModel):
    """An STP subscription from the WFO (the WFO side of the STP reconciliation)."""

    subscription_id: str
    stp_id: str | None = None
    stp_name: str | None = None
    capacity: int | None = None
    label_group: str | None = None
    status: str | None = None


class SdpMember(BaseModel):
    """One of the two STPs that make up an SDP."""

    stp_id: str | None = None
    stp_name: str | None = None
    capacity: int | None = None
    label_group: str | None = None


class SdpSub(BaseModel):
    """An SDP subscription from the WFO (the WFO side of the SDP reconciliation)."""

    subscription_id: str
    sdp_name: str | None = None
    status: str | None = None
    stps: list[SdpMember] = []


class ValidationFailureRow(BaseModel):
    """A failed validation/task process, rendered in the dashboard's validation panel."""

    process_id: str
    workflow_name: str
    last_status: str | None = None
    started_at: str | None = None  # 'YYYY-MM-DD HH:MM:SS'
    failed_reason: str | None = None
    subscription_id: str | None = None  # absent for system tasks, which validate no single subscription
    description: str | None = None
    occurrences: int = 1  # how many processes this row stands for, after deduplication

    @property
    def key(self) -> tuple[str, str | None]:
        """What makes two failures the same problem: the same check on the same subscription."""
        return self.workflow_name, self.subscription_id

    @computed_field  # type: ignore[prop-decorator]
    @property
    def short_id(self) -> str | None:
        return short_id(self.subscription_id)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def reason(self) -> str | None:
        """The failure reason, whitespace-collapsed and truncated for the table."""
        if not self.failed_reason:
            return None
        reason = " ".join(self.failed_reason.split())
        return reason if len(reason) <= _REASON_LENGTH else f"{reason[:_REASON_LENGTH]}…"


def circuit_state_bucket(state: str | None) -> str:
    """Classify a circuit's NSI ``vc.state`` into a tab/dashboard bucket (case-insensitive)."""
    match (state or "").upper():
        case "FAILED":
            return "failed"
        case "RESERVED":
            return "reserved"
        case "TERMINATED":
            return "terminated"
        case _:
            return "activated"


def is_terminated(state: str | None) -> bool:
    """Whether a circuit is gone, as opposed to one that still exists in some form."""
    return circuit_state_bucket(state) == "terminated"


def query_wfo(query: str, token: str | None) -> dict | None:
    """POST a GraphQL query to the WFO, forwarding ``token`` as a Bearer credential.

    Returns the parsed ``data`` object, or ``None`` on transport failure, non-200, non-JSON, or a
    GraphQL ``errors`` payload. Raises :class:`WfoUnauthorizedError` when the WFO refused the
    credentials (401/403, or an authentication/authorization ``errors`` payload).
    """
    log = logger.bind()
    url = f"{str(settings.NSI_AMISS_WFO_URL).rstrip('/')}/api/graphql"
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    try:
        r = session.post(url, json={"query": query}, headers=headers, timeout=REQUEST_TIMEOUT, verify=settings.verify)
    except (requests.exceptions.ConnectionError, requests.exceptions.Timeout) as e:
        log.warning("cannot reach WFO GraphQL", url=url, error=str(e))
        return None
    if r.status_code in (401, 403):
        log.warning("WFO GraphQL refused the credentials", url=url, status=r.status_code)
        raise WfoUnauthorizedError
    if r.status_code != 200:
        log.warning("WFO GraphQL returned non-200", url=url, status=r.status_code, reason=r.reason)
        return None
    try:
        result = json.loads(r.content)
    except (json.JSONDecodeError, ValueError) as e:
        log.warning("cannot parse WFO GraphQL response", url=url, error=str(e))
        return None
    if not isinstance(result, dict):
        log.warning("WFO GraphQL response is not a JSON object", url=url)
        return None
    if result.get("errors"):
        if _is_authz_error(result["errors"]):
            log.warning("WFO GraphQL refused the credentials", url=url, errors=result["errors"])
            raise WfoUnauthorizedError
        log.warning("WFO GraphQL returned errors", errors=result["errors"])
        return None
    data = result.get("data")
    return data if isinstance(data, dict) else None


def _page(data: dict, root: str = "subscriptions") -> list[dict]:
    """Return the ``<root>.page`` list, warning if the page limit truncated the result."""
    node = data.get(root) or {}
    page = node.get("page") or []
    total = (node.get("pageInfo") or {}).get("totalItems")
    if isinstance(total, int) and total > len(page):
        logger.warning("WFO result truncated by page limit", root=root, returned=len(page), total=total)
    return page


def _created_by(sub: dict) -> str | None:
    """Pick the creator: earliest completed CREATE process, else earliest CREATE process."""
    processes = ((sub.get("processes") or {}).get("page")) or []
    completed = next((p for p in processes if p.get("lastStatus") == "completed"), None)
    chosen = completed or (processes[0] if processes else None)
    return chosen.get("createdBy") if chosen else None


def _endpoint(saps: list[dict], index: int) -> tuple[str | None, str | None, str | None]:
    """Return (stp label, stp id, vlan) for ``saps[index]``, tolerating nulls at every level.

    The label is the STP's name where it has one, which is what reads well in a table; the id is kept
    alongside it because it is the only value that joins back to the STP inventory — names are display
    text and do not.
    """
    sap = saps[index] if len(saps) > index else None
    if not sap:
        return None, None, None
    stp = sap.get("stp") or {}
    return (stp.get("stpName") or stp.get("stpId")), stp.get("stpId"), sap.get("vlan")


def _endpoint_label(stp: str | None, vlan: str | None) -> str | None:
    """Combine an endpoint's STP and VLAN into one compact cell, e.g. 'Port A (vlan 100)'."""
    if not stp:
        return None
    return f"{stp} (vlan {vlan})" if vlan else stp


def _format_ts(value: str | None) -> str | None:
    """Format an ISO timestamp as 'YYYY-MM-DD HH:MM:SS' (drop microseconds/timezone) for compact display."""
    if not value:
        return None
    try:
        return datetime.fromisoformat(value).strftime("%Y-%m-%d %H:%M:%S")
    except (ValueError, TypeError):
        return value


def _map_circuit(sub: dict) -> CircuitRow:
    vc = sub.get("vc") or {}
    saps = vc.get("saps") or []
    # saps[0]=source, saps[1]=dest is the create-workflow convention (create_mdp2p.py).
    source_stp, source_stp_id, source_vlan = _endpoint(saps, 0)
    dest_stp, dest_stp_id, dest_vlan = _endpoint(saps, 1)
    subscription_id = sub["subscriptionId"]
    return CircuitRow(
        subscription_id=subscription_id,
        description=vc.get("circuitDescription") or sub.get("description"),
        start_time=_format_ts(sub.get("startDate")),
        end_time=_format_ts(sub.get("endDate")),
        source_stp=source_stp,
        source_stp_id=source_stp_id,
        source_vlan=source_vlan,
        dest_stp=dest_stp,
        dest_stp_id=dest_stp_id,
        dest_vlan=dest_vlan,
        source=_endpoint_label(source_stp, source_vlan),
        dest=_endpoint_label(dest_stp, dest_vlan),
        bandwidth=vc.get("serviceSpeed"),
        state=vc.get("state") or sub.get("status"),
        created_by=_created_by(sub),
        connection_id=vc.get("connectionId"),
        global_reservation_id=vc.get("globalReservationId"),
    )


def _map_stp(sub: dict) -> StpSub:
    stp = sub.get("stp") or {}
    return StpSub(
        subscription_id=sub["subscriptionId"],
        stp_id=stp.get("stpId"),
        stp_name=stp.get("stpName"),
        capacity=stp.get("capacity"),
        label_group=stp.get("labelGroup"),
        status=sub.get("status"),
    )


def _map_sdp(sub: dict) -> SdpSub:
    sdp = sub.get("sdp") or {}
    members = [
        SdpMember(
            stp_id=s.get("stpId"),
            stp_name=s.get("stpName"),
            capacity=s.get("capacity"),
            label_group=s.get("labelGroup"),
        )
        for s in (sdp.get("stps") or [])
    ]
    return SdpSub(
        subscription_id=sub["subscriptionId"], sdp_name=sdp.get("sdpName"), status=sub.get("status"), stps=members
    )


def fetch_circuits(token: str | None) -> list[CircuitRow] | None:
    """Fetch MDP2P circuits from the WFO, or ``None`` on failure."""
    data = query_wfo(CIRCUITS_QUERY, token)
    return None if data is None else [_map_circuit(n) for n in _page(data)]


def fetch_stp_subscriptions(token: str | None) -> list[StpSub] | None:
    """Fetch STP subscriptions from the WFO, or ``None`` on failure."""
    data = query_wfo(STP_QUERY, token)
    return None if data is None else [_map_stp(n) for n in _page(data)]


def fetch_sdp_subscriptions(token: str | None) -> list[SdpSub] | None:
    """Fetch SDP subscriptions from the WFO, or ``None`` on failure."""
    data = query_wfo(SDP_QUERY, token)
    return None if data is None else [_map_sdp(n) for n in _page(data)]


def _map_named(sub: dict, block: str, id_field: str, name_field: str) -> NamedSub:
    values = sub.get(block) or {}
    return NamedSub(
        subscription_id=sub["subscriptionId"],
        object_id=values.get(id_field),
        name=values.get(name_field),
        status=sub.get("status"),
    )


def _fetch_named(query: str, token: str | None, block: str, id_field: str, name_field: str) -> list[NamedSub] | None:
    data = query_wfo(query, token)
    return None if data is None else [_map_named(n, block, id_field, name_field) for n in _page(data)]


def fetch_topology_subscriptions(token: str | None) -> list[NamedSub] | None:
    """Fetch Topology subscriptions from the WFO, or ``None`` on failure."""
    return _fetch_named(TOPOLOGY_QUERY, token, "topology", "topologyId", "topologyName")


def fetch_switching_service_subscriptions(token: str | None) -> list[NamedSub] | None:
    """Fetch SwitchingService subscriptions from the WFO, or ``None`` on failure."""
    return _fetch_named(
        SWITCHING_SERVICE_QUERY, token, "switchingservice", "switchingServiceId", "switchingServiceName"
    )


def _map_validation_failure(process: dict) -> ValidationFailureRow:
    subscription: dict = next(iter(((process.get("subscriptions") or {}).get("page")) or []), {})
    return ValidationFailureRow(
        process_id=process["processId"],
        workflow_name=process["workflowName"],
        last_status=process.get("lastStatus"),
        started_at=_format_ts(process.get("startedAt")),
        failed_reason=process.get("failedReason"),
        subscription_id=subscription.get("subscriptionId"),
        description=subscription.get("description"),
    )


def dedupe_failures(rows: list[ValidationFailureRow]) -> list[ValidationFailureRow]:
    """Collapse repeated failures of the same check on the same subscription into one counted row.

    Rows arrive newest first; iterating oldest-first lets the later write win, so the surviving row is
    the most recent, and reversing restores newest-first order.
    """
    counts = Counter(row.key for row in rows)
    newest = {row.key: row for row in reversed(rows)}
    return [row.model_copy(update={"occurrences": counts[row.key]}) for row in reversed(newest.values())]


def fetch_validation_failures(token: str | None) -> list[ValidationFailureRow] | None:
    """Fetch failed validation and system-task processes from the WFO, or ``None`` on failure."""
    data = query_wfo(VALIDATION_FAILURES_QUERY, token)
    return None if data is None else dedupe_failures([_map_validation_failure(p) for p in _page(data, "processes")])
