# Copyright 2024-2026 SURF.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Query the WFO orchestrator GraphQL API and map results into render DTOs.

The end-user's OIDC token is forwarded per request as a Bearer credential; the orchestrator validates
it (SRAM userinfo) and enforces the operators group. Every fetch returns ``None`` on any failure
(transport, non-200, non-JSON, GraphQL errors) so callers can tell "failed" apart from "empty".
"""

import json
from datetime import datetime

import requests
import structlog
from pydantic import BaseModel

from amiss.nsi import REQUEST_TIMEOUT, session
from amiss.settings import settings

logger = structlog.get_logger(__name__)

# Concrete GraphQL subscription type names (auto-generated by orchestrator-core from the product
# base-type names) and product tags. Confirm once via live introspection before shipping.
MDP2P_TYPE = "MultiDomainPoint2PointSubscription"
STP_TYPE = "ServiceTerminationPointSubscription"
SDP_TYPE = "ServiceDemarcationPointSubscription"

CIRCUITS_QUERY = """
{ subscriptions(first: 500, filterBy: [{field: "tag", value: "MDP2P"}]) {
  page {
    subscriptionId description status startDate endDate
    ... on %(mdp2p)s { vc {
      circuitDescription serviceSpeed globalReservationId connectionId state
      saps { vlan stp { stpId stpName capacity labelGroup } } } }
    processes(filterBy: [{field: "target", value: "CREATE"}],
              sortBy: [{field: "startedAt", order: ASC}], first: 10) {
      page { createdBy startedAt lastStatus } }
  }
  pageInfo { totalItems }
} }
""" % {"mdp2p": MDP2P_TYPE}

STP_QUERY = """
{ subscriptions(first: 1000, filterBy: [{field: "tag", value: "STP"}]) {
  page { subscriptionId status
    ... on %(stp)s { stp { stpId stpName capacity labelGroup } } }
  pageInfo { totalItems }
} }
""" % {"stp": STP_TYPE}

SDP_QUERY = """
{ subscriptions(first: 1000, filterBy: [{field: "tag", value: "SDP"}]) {
  page { subscriptionId status
    ... on %(sdp)s { sdp { sdpName stps { stpId stpName labelGroup } } } }
  pageInfo { totalItems }
} }
""" % {"sdp": SDP_TYPE}


class CircuitRow(BaseModel):
    """A circuit row rendered in /circuits, built live from an MDP2P subscription."""

    subscription_id: str
    short_id: str | None = None  # first 8 chars of subscription_id, shown in the list; full id on detail
    description: str | None = None
    start_time: str | None = None  # 'YYYY-MM-DD HH:MM:SS' (compact, wraps on the space)
    end_time: str | None = None
    source_stp: str | None = None
    source_vlan: str | None = None
    dest_stp: str | None = None
    dest_vlan: str | None = None
    source: str | None = None  # 'stp (vlan N)' for the compact list; raw stp/vlan (above) shown on detail
    dest: str | None = None
    bandwidth: int | None = None
    state: str | None = None
    created_by: str | None = None
    connection_id: str | None = None
    global_reservation_id: str | None = None


class StpSub(BaseModel):
    """An STP subscription from the WFO (the WFO side of the STP reconciliation)."""

    subscription_id: str
    stp_id: str | None = None
    stp_name: str | None = None
    capacity: int | None = None
    label_group: str | None = None
    status: str | None = None


class SdpMember(BaseModel):
    """One of the two STPs that make up an SDP."""

    stp_id: str | None = None
    stp_name: str | None = None
    label_group: str | None = None


class SdpSub(BaseModel):
    """An SDP subscription from the WFO (the WFO side of the SDP reconciliation)."""

    subscription_id: str
    sdp_name: str | None = None
    status: str | None = None
    stps: list[SdpMember] = []


def circuit_state_bucket(state: str | None) -> str:
    """Classify a circuit's NSI ``vc.state`` into a tab/dashboard bucket (case-insensitive)."""
    match (state or "").upper():
        case "FAILED":
            return "failed"
        case "TERMINATED":
            return "terminated"
        case _:
            return "activated"


def query_wfo(query: str, token: str | None) -> dict | None:
    """POST a GraphQL query to the WFO, forwarding ``token`` as a Bearer credential.

    Returns the parsed ``data`` object, or ``None`` on transport failure, non-200, non-JSON, or a
    GraphQL ``errors`` payload (e.g. the ``not_authenticated`` response when no valid token is sent).
    """
    log = logger.bind()
    url = f"{str(settings.NSI_AMISS_WFO_URL).rstrip('/')}/api/graphql"
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    try:
        r = session.post(url, json={"query": query}, headers=headers, timeout=REQUEST_TIMEOUT, verify=settings.verify)
    except (requests.exceptions.ConnectionError, requests.exceptions.Timeout) as e:
        log.warning("cannot reach WFO GraphQL", url=url, error=str(e))
        return None
    if r.status_code != 200:
        log.warning("WFO GraphQL returned non-200", url=url, status=r.status_code, reason=r.reason)
        return None
    try:
        result = json.loads(r.content)
    except (json.JSONDecodeError, ValueError) as e:
        log.warning("cannot parse WFO GraphQL response", url=url, error=str(e))
        return None
    if not isinstance(result, dict):
        log.warning("WFO GraphQL response is not a JSON object", url=url)
        return None
    if result.get("errors"):
        log.warning("WFO GraphQL returned errors", errors=result["errors"])
        return None
    data = result.get("data")
    return data if isinstance(data, dict) else None


def _page(data: dict) -> list[dict]:
    """Return the ``subscriptions.page`` list, warning if the page limit truncated the result."""
    subscriptions = data.get("subscriptions") or {}
    page = subscriptions.get("page") or []
    total = (subscriptions.get("pageInfo") or {}).get("totalItems")
    if isinstance(total, int) and total > len(page):
        logger.warning("WFO result truncated by page limit", returned=len(page), total=total)
    return page


def _created_by(sub: dict) -> str | None:
    """Pick the creator: earliest completed CREATE process, else earliest CREATE process."""
    processes = ((sub.get("processes") or {}).get("page")) or []
    completed = next((p for p in processes if p.get("lastStatus") == "completed"), None)
    chosen = completed or (processes[0] if processes else None)
    return chosen.get("createdBy") if chosen else None


def _endpoint(saps: list[dict], index: int) -> tuple[str | None, str | None]:
    """Return (stp label, vlan) for ``saps[index]``, tolerating nulls at every level."""
    sap = saps[index] if len(saps) > index else None
    if not sap:
        return None, None
    stp = sap.get("stp") or {}
    return (stp.get("stpName") or stp.get("stpId")), sap.get("vlan")


def _endpoint_label(stp: str | None, vlan: str | None) -> str | None:
    """Combine an endpoint's STP and VLAN into one compact cell, e.g. 'Port A (vlan 100)'."""
    if not stp:
        return None
    return f"{stp} (vlan {vlan})" if vlan else stp


def _format_ts(value: str | None) -> str | None:
    """Format an ISO timestamp as 'YYYY-MM-DD HH:MM:SS' (drop microseconds/timezone) for compact display."""
    if not value:
        return None
    try:
        return datetime.fromisoformat(value).strftime("%Y-%m-%d %H:%M:%S")
    except (ValueError, TypeError):
        return value


def _map_circuit(sub: dict) -> CircuitRow:
    vc = sub.get("vc") or {}
    saps = vc.get("saps") or []
    # saps[0]=source, saps[1]=dest is the create-workflow convention (create_mdp2p.py).
    source_stp, source_vlan = _endpoint(saps, 0)
    dest_stp, dest_vlan = _endpoint(saps, 1)
    subscription_id = sub["subscriptionId"]
    return CircuitRow(
        subscription_id=subscription_id,
        short_id=subscription_id[:8],
        description=vc.get("circuitDescription") or sub.get("description"),
        start_time=_format_ts(sub.get("startDate")),
        end_time=_format_ts(sub.get("endDate")),
        source_stp=source_stp,
        source_vlan=source_vlan,
        dest_stp=dest_stp,
        dest_vlan=dest_vlan,
        source=_endpoint_label(source_stp, source_vlan),
        dest=_endpoint_label(dest_stp, dest_vlan),
        bandwidth=vc.get("serviceSpeed"),
        state=vc.get("state") or sub.get("status"),
        created_by=_created_by(sub),
        connection_id=vc.get("connectionId"),
        global_reservation_id=vc.get("globalReservationId"),
    )


def _map_stp(sub: dict) -> StpSub:
    stp = sub.get("stp") or {}
    return StpSub(
        subscription_id=sub["subscriptionId"],
        stp_id=stp.get("stpId"),
        stp_name=stp.get("stpName"),
        capacity=stp.get("capacity"),
        label_group=stp.get("labelGroup"),
        status=sub.get("status"),
    )


def _map_sdp(sub: dict) -> SdpSub:
    sdp = sub.get("sdp") or {}
    members = [
        SdpMember(stp_id=s.get("stpId"), stp_name=s.get("stpName"), label_group=s.get("labelGroup"))
        for s in (sdp.get("stps") or [])
    ]
    return SdpSub(
        subscription_id=sub["subscriptionId"], sdp_name=sdp.get("sdpName"), status=sub.get("status"), stps=members
    )


def fetch_circuits(token: str | None) -> list[CircuitRow] | None:
    """Fetch MDP2P circuits from the WFO, or ``None`` on failure."""
    data = query_wfo(CIRCUITS_QUERY, token)
    return None if data is None else [_map_circuit(n) for n in _page(data)]


def fetch_stp_subscriptions(token: str | None) -> list[StpSub] | None:
    """Fetch STP subscriptions from the WFO, or ``None`` on failure."""
    data = query_wfo(STP_QUERY, token)
    return None if data is None else [_map_stp(n) for n in _page(data)]


def fetch_sdp_subscriptions(token: str | None) -> list[SdpSub] | None:
    """Fetch SDP subscriptions from the WFO, or ``None`` on failure."""
    data = query_wfo(SDP_QUERY, token)
    return None if data is None else [_map_sdp(n) for n in _page(data)]
